import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/nevbar";
import { Nunito } from "next/font/google";
import Footer from "./components/footer";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css'; // Import CSS
config.autoAddCss = false; 



const inter = Nunito({ weight: "400", subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className}`}
      >
       
        <Navbar />
        {children}
         {/* Floating Icons */}
      <div className="fixed bottom-16 right-10 flex flex-col gap-4 z-50">
        <a
          href="https://github.com/DnopPondz"
          target="_blank"
          rel="noopener noreferrer"
        >
          <i className="bx bxl-github text-4xl transition-transform duration-500 ease-in-out hover:scale-110 text-[#fcda68]"></i>
        </a>
        <a
          href="https://www.linkedin.com/in/wachirodol-thongnate-6b6b24313/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <i className="bx bxl-linkedin text-4xl transition-transform duration-500 ease-in-out hover:scale-110 text-[#fcda68]"></i>
        </a>
      </div>
        <Footer />
        
        
      </body>
    </html>
  );
}
